apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: "aap-soknad-behandling"
  namespace: "aap"
  labels:
    "team": "aap"
    "start.nais.io/created-by": "me"
    "start.nais.io/creationTimestamp": "2021-09-22T08:16:29.964216528"
spec:
  receivers:
    slack:
      channel: "aap-alerts-prod"
      prependText: "<!here> | "
  alerts:
  - alert: "aap-soknad-behandling er nede"
    description: "App {{ $labels.app }} er nede i namespace {{ $labels.kubernetes_namespace\
      \ }}"
    expr: "kube_deployment_status_replicas_available{deployment=\"aap-soknad\"} >\
      \ 0"
    for: "2m"
    action: "kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace\
      \ }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace\
      \ }}` for logger"
    documentation: "https://github.com/navikt/aap/somedoc"
    sla: "Responder innen 1 time i kontortid"
    severity: "danger"
  - alert: "Mye feil i loggene"
    expr: "(100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app=\"\
      aap-soknad\",log_level=~\"Warning|Error\"}[3m])) / sum by (log_app, log_namespace)\
      \ (rate(logd_messages_total{log_app=\"aap-soknad\"}[3m]))) > 10"
    for: "3m"
    action: "Sjekk loggene til app {{ $labels.log_app }} i namespace {{ $labels.log_namespace\
      \ }} for å se hvorfor det er så mye feil"
    sla: "Responder innen 1 time i kontortid"
    severity: "warning"