ingresses:
- "https://aap-soknad-behandling.dev.intern.nav.no"
env:
- name: APP_URL
  value: "https://aap-soknad.dev.nav.no"
- name: SOKNAD_API_URL
  value: "http://apparat"
- name: SOKNAD_API_AUDIENCE
  value: "dev-gcp:aap:apparat"
- name: API_SCOPE
  value: "api://dev-gcp.aap.apparat/.default"
