ingresses:
- "https://aap-soknad-behandling.dev.intern.nav.no"
env:
- name: APP_URL
  value: "https://aap-soknad.dev.nav.no"
- name: SOKNAD_API_URL
  value: "https://apparat.dev.intern.nav.no"
- name: SOKNAD_API_AUDIENCE
  value: "dev-gcp:aap:apparat"
