ingresses:
- "https://aap-soknad-behandling.dev.intern.nav.no"
env:
- name: APP_URL
  value: "https://aap-soknad-behandling.dev.intern.nav.no"
- name: OPPGAVESTYRING_API_URL
  value: "http://oppgavestyring"
- name: OPPGAVESTYRING_API_AUDIENCE
  value: "dev-gcp:aap:oppgavestyring"
- name: OPPGAVESTYRING_API_SCOPE
  value: "api://dev-gcp.aap.oppgavestyring/.default"
