ingresses:
- "https://aap-soknad-behandling.dev.intern.nav.no"
env:
- name: APP_URL
  value: "https://aap-soknad-behandling.dev.intern.nav.no"
- name: SOKNAD_API_URL
  value: "http://vedtak"
- name: SOKNAD_API_AUDIENCE
  value: "dev-gcp:aap:vedtak"
- name: API_SCOPE
  value: "api://dev-gcp.aap.vedtak/.default"
