ingresses:
- "https://aap-soknad-behandling.dev.intern.nav.no"
env:
- name: APP_URL
  value: "https://aap-soknad-behandling.dev.intern.nav.no"
- name: VEDTAK_API_URL
  value: "http://vedtak"
- name: VEDTAK_API_AUDIENCE
  value: "dev-gcp:aap:vedtak"
- name: VEDTAK_API_SCOPE
  value: "api://dev-gcp.aap.vedtak/.default"
- name: OPPGAVEBEHANDLING_API_URL
  value: "http://oppgavestyring"
- name: OPPGAVEBEHANDLING_API_AUDIENCE
  value: "dev-gcp:aap:oppgavestyring"
- name: OPPGAVEBEHANDLING_API_SCOPE
  value: "api://dev-gcp.aap.oppgavebehandling/.default"
kafka-pool:
- nav-dev
